name: Publish Signed Firefox Extension

on: [push]

jobs:
  load-json:
    runs-on: ubuntu-latest
    outputs:
      RUN: ${{ steps.load_json.outputs.RUN }}
      TAG: ${{ steps.load_json.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Tag ${{ github.ref }}
        id: load_json
        run: |
          manifestVersion=$(cat ./manifest.json | jq -r '.version' )
          echo "VERSION: $manifestVersion"
          if(( $(git tag -l "$manifestVersion" | wc -c ) == 0 )); then
            echo "NEW VERSION"
            echo "RUN=true" >> "$GITHUB_OUTPUT"
            echo "TAG=$manifestVersion" >> "$GITHUB_OUTPUT"
          else
            echo "VERSION ALREADY EXISTS"
            echo "RUN=false" >> "$GITHUB_OUTPUT"
          fi

  build-and-publish:
    needs: [load-json]
    if: ${{ needs.load-json.outputs.RUN }} == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md

      - name: Web-ext Build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./

      - name: Web-ext Sign
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.JWT_ISSUER }}
          apiSecret: ${{ secrets.JWT_SECRET }}
          timeout: 900000

      - name: Rename Output
        id: rename-web-ext
        run: |
          mv ${{ steps.web-ext-sign.outputs.target }} ${{ github.event.repository.name }}.xpi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: "refs/tags/${{ needs.load-json.outputs.TAG }}"
          artifacts: "${{ github.event.repository.name }}.xpi"
          bodyFile: "${{ github.workspace }}-CHANGELOG.md"
          token: ${{ secrets.FF_RELEASE_TOKEN }}






