name: Publish Signed Firefox Extension

on:
  push:
    branches: [ main ]
    tags: 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ env.JWT_ISSUER }}
          apiSecret: ${{ env.JWT_SECRET }}
          timeout: 900000

      - name: "Create Release"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name}}.xpi
          path: ${{ steps.web-ext-build.outputs.target }}


