name: Publish Signed Firefox Extension

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./
          filename: "${{ github.event.repository.name }}.xpi"

      - name: Add Source To Release
        id: zipped-source
        run: zip -r source-code.zip . -x "\.*" "*.zip" "*.xpi" "*CHANGELOG.md" "web-ext-artifacts/"


      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "${{ steps.web-ext-build.outputs.target }}, ${{ steps.zip-source.outputs.target }}"
          bodyFile: "${{ github.workspace }}-CHANGELOG.md"
          tag: "v1.0.3"
          token: ${{ secrets.FF_RELEASE_TOKEN }}




