name: Publish Signed Firefox Extension

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build XPI extension
        uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
        with:
          zipFilePath: build/${{ github.event.repository.name }}.zip
          xpiFilePath: build/${{ github.event.repository.name }}.xpi
          jwtIssuer: ${{ env.JWT_ISSUER }}
          jwtSecret: ${{ env.JWT_SECRET }}

      - name: Upload signed extension
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name}}.xpi
          path: build/${{ github.event.repository.name }}.xpi


