name: Publish Signed Firefox Extension

on:
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-tag.outputs.run_jobs }}
      tag_val: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Check Tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo ::set-output name=run_jobs::true
            echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=run_jobs::false
          fi

  build-and-publish:
    needs: [check_tag]
    if: needs.check_tag.outputs.run_other_jobs == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Changelog and Get Tag Version
        run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md

      - name: Add Source To Release
        id: zipped-source
        run: zip -r source-code.zip . -x "\.*" "*.zip" "*.xpi" "*CHANGELOG.md" "web-ext-artifacts/"

      - name: Web-ext Build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ needs.check_tag.outputs.tag_val }}
          artifacts: "${{ steps.web-ext-build.outputs.target }}, source-code.zip"
          bodyFile: "${{ github.workspace }}-CHANGELOG.md"
          token: ${{ secrets.FF_RELEASE_TOKEN }}









