name: Publish Signed Firefox Extension

on: [push]

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-tag.outputs.run_jobs }}
      tag_val: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Tag ${{ github.ref }}
        id: load-json
        run: |
          manifestVersion=$(cat ./manifest.json | jq '.version')
          lastVersion=$(git tag -l --sort=-version:refname | head -1)
          echo $manifestVersion $lastVersion
          if[[ $manifestVersion -eq $lastVersion ]] then
            echo "No match!"
          else
            echo "Match!"
          fi
          

  build-and-publish:
    needs: [check_tag]
    if: needs.check_tag.outputs.run_other_jobs == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md

      - name: Web-ext Build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./

      - name: Web-ext Sign
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.JWT_ISSUER }}
          apiSecret: ${{ secrets.JWT_SECRET }}
          timeout: 900000

      - name: Rename Output
        id: rename-web-ext
        run: |
          mv ${{ steps.web-ext-sign.outputs.target }} ${{ github.event.repository.name }}.xpi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ needs.check_tag.outputs.tag_val }}
          artifacts: "${{ github.event.repository.name }}.xpi"
          bodyFile: "${{ github.workspace }}-CHANGELOG.md"
          token: ${{ secrets.FF_RELEASE_TOKEN }}









