name: Publish Signed Firefox Extension

on:
  push:
    branches: [ main ]


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt"

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./
          filename: "${{ github.event.repository.name }}.xpi"


      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FF_RELEASE_TOKEN }}
        with:
          draft: true
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: ${{ steps.web-ext-build.outputs.target }}


