name: Publish Signed Firefox Extension

on:
  create:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  load-json:
    runs-on: ubuntu-latest
    outputs:
      RUN: ${{ steps.validateVersion.outputs.RUN }}
      TAG: ${{ steps.validateVersion.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Tag ${{ github.ref }}
        id: validateVersion
        run: |
          ref="${GITHUB_REF#refs/tags/}"

          if [[ "$ref" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "run_jobs=true" >> "$GITHUB_OUTPUT"
            echo "tag=$ref" >> "$GITHUB_OUTPUT"
            echo "✅ Detected version tag: $ref"
          else
            echo "run_jobs=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ Not a version tag: $GITHUB_REF"
          fi

  build-and-publish:
    needs: [load-json]
    if: ${{ needs.load-json.outputs.RUN == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md

      - name: Web-ext Build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: build
          source: ./

      - name: Web-ext Sign
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.JWT_ISSUER }}
          apiSecret: ${{ secrets.JWT_SECRET }}
          timeout: 900000

      - name: Rename Output
        id: rename-web-ext
        run: |
          mv ${{ steps.web-ext-sign.outputs.target }} ${{ github.event.repository.name }}.xpi

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          draft: true
          tag: "refs/tags/${{ needs.load-json.outputs.TAG }}"
          artifacts: "${{ github.event.repository.name }}.xpi"
          bodyFile: "${{ github.workspace }}-CHANGELOG.md"
          # token: ${{ secrets.FF_RELEASE_TOKEN }}






