name: Publish Signed Firefox Extension

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-tag.outputs.run_jobs }}
      tag_val: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Check Tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/v[0-9]+\.[0-9]+\.0\.[0-9]+ ]]; then
            echo ::set-output name=run_jobs::true
            echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=run_jobs::false
          fi

  test_output:
    needs: [check_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Check output
        run: echo ${{ needs.check_tag.outputs.run_other_jobs }} && echo ${{ needs.check_tag.outputs.tag_val }}









